services:
  cloudflare-ddns:
    container_name: krispy-ddns
    image: oznu/cloudflare-ddns
    restart: always
    environment:
      - API_KEY=$API_KEY
      - ZONE=$DOMAIN
      - PROXIED=true

  nginx:
    container_name: krispy-nginx
    build: nginx
    restart: always
    ports:
      - 443:443
    environment:
      - DOMAIN=$DOMAIN
      - PORT=443
    volumes:
      - ./app/page:/usr/share/nginx/html
      - ./private/certs:/etc/nginx/certs
      - ./private/passwd:/var/lib/nginx
      - ./private/logs:/var/log/nginx

  # Coming Soon..
  # app:
  # container_name: krispy-app
  #  build:
