services:
  nginx:
    container_name: krispy-nginx
    build: nginx
    restart: always
    ports:
      - $PORT:443
    environment:
      - DOMAIN=$DOMAIN
    volumes:
      - $LOG:/var/log/nginx
      - /etc/nginx/certs:/etc/nginx/certs

  ddns:
    container_name: krispy-ddns
    image: oznu/cloudflare-ddns
    restart: always
    environment:
      - PROXIED=true
      - ZONE=$DOMAIN
      - API_KEY=$DDNS_API_KEY

  # Coming Soon..
  # app:
  # container_name: krispy-app
  #  build: app
  #  restart: always

  # selenium:
  #   container_name: krispy-selenium
  #   build: selenium
  #   restart: always
